#!/usr/bin/env python

import operator

import matplotlib.pyplot as plt
import numpy as np


#==========================================================================
## Fetch the data
#==========================================================================

data_file = 'data'

letters = {}
login_lengths = []

with open(data_file, 'r') as f:
    for line in f:
        letter = line[0]
        if letter in letters:
            letters[letter] += 1
        else:
            letters[letter] = 0
        login_lengths.append((line, len(line)))

# Initial letters
sorted_letters = sorted(letters.iteritems(), key=operator.itemgetter(1),
                        reverse=True)
# print(sorted_letters)  # DEBUG

# Login lengths
login_lengths = sorted(login_lengths, key=lambda elem: (elem[1], elem[0]),
                       reverse=True)
# print(login_lengths)  # DEBUG


#==========================================================================
# Plot
#==========================================================================

def plot(data):
    fig = plt.figure()
    ax = fig.add_subplot(111)
    
    
    # Plot bars
    # ax.plot(lengths)
    BAR_WIDTH = 20
    for i, freq in enumerate(data):
        ax.bar(i * BAR_WIDTH, freq, BAR_WIDTH, color='#00ffaa',
               edgecolor='#000055', alpha=.5)
    
    # Plot a series of lines
    stretch= [i * BAR_WIDTH + (BAR_WIDTH / 2) for i, j in enumerate(data)]
    ax.plot(stretch, data, '-r', linewidth=3, alpha=.5)
    
    # Plot the mean line
    mean = np.mean(data)
    mean_line = [mean for i in data]
    ax.plot(stretch, mean_line, '-g', linewidth=3, alpha=1)

    plt.show()


# data = [i[1] for i in sorted_letters]
data = [i[1] for i in login_lengths]
plot(data)
